from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

from filterx.core.config import load_effective_config
from filterx.core.io import load_json
from filterx.core.ir import FilterxIR, ir_from_dict
from filterx.core.patcher import PatchOp, apply_patch_operations

from .base import RendererTarget


def _ts_import(from_file: Path, target: Path, *, node_next: bool) -> str:
    relative = os.path.relpath(target, from_file.parent).replace("\\", "/")
    if not relative.startswith("."):
        relative = f"./{relative}"
    if node_next:
        relative = f"{relative}.js"
    return relative


def _node_next(project_root: Path, tsconfig_path: str) -> bool:
    path = project_root / tsconfig_path
    if not path.exists():
        return False
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return False
    module = str(document.get("compilerOptions", {}).get("module", "")).lower()
    return module in {"node16", "nodenext"}


def _render_metadata(ir: FilterxIR) -> str:
    payload = json.dumps(ir.to_dict(), indent=2)
    return (
        "// Generated by FilterX. Do not edit.\n"
        "import type { FilterxIR } from './types.js';\n\n"
        f"export const filterxMetadata = {payload} as const satisfies FilterxIR;\n"
    )


def _render_types() -> str:
    return """// Generated by FilterX. Do not edit.
import type { Request } from 'express';

export type FilterOperation =
  | 'eq' | 'ne' | 'gt' | 'gte' | 'lt' | 'lte'
  | 'like' | 'ilike' | 'starts_with' | 'ends_with'
  | 'in' | 'not_in' | 'between' | 'is_null' | 'is_not_null';

export interface FilterCondition {
  node_type?: 'condition';
  field: string;
  operation: FilterOperation;
  value?: unknown;
}

export interface FilterGroup {
  node_type: 'operator';
  operator: 'AND' | 'OR';
  children: FilterNode[];
}

export type FilterNode = FilterCondition | FilterGroup;
export interface FilterBody { filters?: FilterCondition[]; filter_tree?: FilterNode | null }
export interface PageMeta { page: number; size: number; total_items: number; total_pages: number }
export interface PageResponse<T = Record<string, unknown>> { data: T[]; meta: PageMeta }
export interface FilterxErrorBody { error: { code: string; message: string; details?: unknown } }

export interface IRField {
  name: string; type: string; source_type: string; nullable: boolean; primary_key: boolean;
  unique: boolean; has_default: boolean; foreign_keys: readonly string[];
  operations: readonly string[]; enum_values: readonly string[]; visibility: string; permission: string | null;
}
export interface IRRelationship {
  name: string; kind: string; target_entity: string; target_table: string;
  join_path: readonly string[]; depth: number; collection: boolean; back_populates: string | null; cycle: boolean;
}
export interface IREntity {
  name: string;
  identity: { module: string; table: string; primary_keys: readonly string[] };
  fields: readonly IRField[];
  relationships: readonly IRRelationship[];
  cycle_memberships: readonly (readonly string[])[];
  soft_delete: { respected: boolean; field: string | null };
}
export interface FilterxIR {
  version: 'filterx-ir/v1'; source_framework: string; entities: readonly IREntity[];
  routes: readonly unknown[]; security: unknown; max_relationship_depth: number;
}

export interface FilterxHooks {
  extractIdentity(request: Request): unknown | Promise<unknown>;
  rowPredicate(context: { principal: unknown; request: Request; entity: IREntity; action: string }):
    Record<string, unknown> | null | undefined | Promise<Record<string, unknown> | null | undefined>;
  fieldVisible(context: {
    principal: unknown; request: Request; entity: IREntity; field: string; action: string;
  }): boolean | Promise<boolean>;
}
"""


def _render_validation() -> str:
    return """// Generated by FilterX. Do not edit.
import { z } from 'zod';

export const conditionSchema = z.object({
  node_type: z.literal('condition').optional(),
  field: z.string().min(1),
  operation: z.enum([
    'eq', 'ne', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike', 'starts_with', 'ends_with',
    'in', 'not_in', 'between', 'is_null', 'is_not_null',
  ]),
  value: z.unknown().optional(),
});

export const filterNodeSchema: z.ZodType<unknown> = z.lazy(() => z.union([
  conditionSchema,
  z.object({
    node_type: z.literal('operator'),
    operator: z.enum(['AND', 'OR']),
    children: z.array(filterNodeSchema).min(1),
  }),
]));

export const filterBodySchema = z.object({
  filters: z.array(conditionSchema).optional().default([]),
  filter_tree: filterNodeSchema.nullish(),
}).default({ filters: [] });

export const paginationSchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  size: z.coerce.number().int().min(1).max(100).default(20),
  sort_by: z.string().min(1).optional(),
  order: z.enum(['asc', 'desc']).default('asc'),
  search: z.string().optional(),
});
"""


def _render_query(prisma_provider: str) -> str:
  case_insensitive = (
    "{ contains: String(value), mode: 'insensitive' }"
    if prisma_provider in {"postgresql", "mongodb"}
    else "{ contains: String(value) }"
  )
  return """// Generated by FilterX. Do not edit.
import type { FilterCondition, FilterNode, IREntity, IRField, IRRelationship } from './types.js';

export class FilterxQueryError extends Error {
  constructor(public readonly code: string, message: string, public readonly details?: unknown) {
    super(message);
  }
}

function resolveField(entity: IREntity, entities: readonly IREntity[], path: string): { field: IRField; relationships: IRRelationship[] } {
  const parts = path.split('.');
  const fieldName = parts.pop() ?? path;
  const relationships: IRRelationship[] = [];
  let current = entity;
  for (const relationshipName of parts) {
    const relationship = current.relationships.find((candidate) => candidate.name === relationshipName);
    if (!relationship) throw new FilterxQueryError('RELATIONSHIP_UNKNOWN', `Unknown relationship '${relationshipName}' in '${path}'.`);
    relationships.push(relationship);
    const target = entities.find((candidate) => candidate.name === relationship.target_entity);
    if (!target) throw new FilterxQueryError('RELATIONSHIP_TARGET_UNAVAILABLE', `Relationship target '${relationship.target_entity}' is not present in FilterX metadata.`);
    current = target;
  }
  const field = current.fields.find((candidate) => candidate.name === fieldName);
  if (!field) throw new FilterxQueryError('FIELD_UNKNOWN', `Unknown filter field '${path}'.`);
  return { field, relationships };
}

function coerce(field: IRField, value: unknown): unknown {
  if (value === null || value === undefined) return value;
  if (Array.isArray(value)) return value.map((item) => coerce(field, item));
  if (field.type === 'integer') {
    const parsed = Number(value);
    if (!Number.isInteger(parsed)) throw new FilterxQueryError('VALUE_INVALID', `Field '${field.name}' expects an integer.`);
    return parsed;
  }
  if (field.type === 'decimal') {
    const parsed = Number(value);
    if (!Number.isFinite(parsed)) throw new FilterxQueryError('VALUE_INVALID', `Field '${field.name}' expects a number.`);
    return value;
  }
  if (field.type === 'boolean') {
    if (value === true || value === false) return value;
    if (String(value).toLowerCase() === 'true') return true;
    if (String(value).toLowerCase() === 'false') return false;
    throw new FilterxQueryError('VALUE_INVALID', `Field '${field.name}' expects a boolean.`);
  }
  if (field.type === 'date' || field.type === 'datetime') {
    const parsed = new Date(String(value));
    if (Number.isNaN(parsed.valueOf())) throw new FilterxQueryError('VALUE_INVALID', `Field '${field.name}' expects an ISO date.`);
    return parsed;
  }
  if (field.type === 'enum' && field.enum_values.length && !field.enum_values.includes(String(value))) {
    throw new FilterxQueryError('VALUE_INVALID', `Field '${field.name}' expects one of: ${field.enum_values.join(', ')}.`);
  }
  return value;
}

function scalarCondition(field: IRField, operation: string, rawValue: unknown): unknown {
  if (!field.operations.includes(operation)) {
    throw new FilterxQueryError('OPERATION_UNSUPPORTED', `Operation '${operation}' is not valid for '${field.name}'.`);
  }
  const value = coerce(field, rawValue);
  switch (operation) {
    case 'eq': return value;
    case 'ne': return { not: value };
    case 'gt': case 'gte': case 'lt': case 'lte': return { [operation]: value };
    case 'in': return { in: Array.isArray(value) ? value : [value] };
    case 'not_in': return { notIn: Array.isArray(value) ? value : [value] };
    case 'between': {
      if (!Array.isArray(value) || value.length !== 2) throw new FilterxQueryError('VALUE_INVALID', 'between expects two values.');
      return { gte: value[0], lte: value[1] };
    }
    case 'is_null': return null;
    case 'is_not_null': return { not: null };
    case 'like': return { contains: String(value) };
    case 'ilike': return __FILTERX_CASE_INSENSITIVE__;
    case 'starts_with': return { startsWith: String(value) };
    case 'ends_with': return { endsWith: String(value) };
    default: throw new FilterxQueryError('OPERATION_UNSUPPORTED', `Unsupported operation '${operation}'.`);
  }
}

function nestRelationships(relationships: readonly IRRelationship[], field: string, condition: unknown): Record<string, unknown> {
  let nested: Record<string, unknown> = { [field]: condition };
  for (const relationship of [...relationships].reverse()) {
    nested = { [relationship.name]: relationship.collection ? { some: nested } : { is: nested } };
  }
  return nested;
}

export function buildCondition(entity: IREntity, entities: readonly IREntity[], condition: FilterCondition): Record<string, unknown> {
  const resolved = resolveField(entity, entities, condition.field);
  return nestRelationships(resolved.relationships, resolved.field.name, scalarCondition(resolved.field, condition.operation, condition.value));
}

export function buildTree(entity: IREntity, entities: readonly IREntity[], node: FilterNode | null | undefined): Record<string, unknown> {
  if (!node) return {};
  if ('operator' in node && node.node_type === 'operator') {
    return { [node.operator]: node.children.map((child) => buildTree(entity, entities, child)) };
  }
  return buildCondition(entity, entities, node as FilterCondition);
}

export function queryCost(filters: readonly FilterCondition[], tree: FilterNode | null | undefined): number {
  let cost = filters.reduce((total, filter) => total + 1 + filter.field.split('.').length, 0);
  const visit = (node: FilterNode | null | undefined, depth: number): void => {
    if (!node) return;
    cost += depth;
    if ('children' in node) node.children.forEach((child) => visit(child, depth + 1));
    else cost += node.field.split('.').length;
  };
  visit(tree, 1);
  return cost;
}

export function buildSearch(entity: IREntity, search: string | undefined): Record<string, unknown> {
  if (!search) return {};
  const fields = entity.fields.filter((field) => field.type === 'string' && field.operations.includes('ilike'));
  return { OR: fields.map((field) => ({ [field.name]: __FILTERX_CASE_INSENSITIVE_SEARCH__ })) };
}

export function combineWhere(...parts: Array<Record<string, unknown> | null | undefined>): Record<string, unknown> {
  const active = parts.filter((part) => part && Object.keys(part).length) as Record<string, unknown>[];
  if (!active.length) return {};
  if (active.length === 1) return active[0];
  return { AND: active };
}

export function buildOrderBy(entity: IREntity, entities: readonly IREntity[], field: string | undefined, order: 'asc' | 'desc'): Record<string, unknown> {
  const selected = field ?? entity.identity.primary_keys[0] ?? entity.fields[0]?.name;
  if (!selected) return {};
  const resolved = resolveField(entity, entities, selected);
  if (resolved.relationships.some((relationship) => relationship.collection)) {
    throw new FilterxQueryError('SORT_FIELD_UNSUPPORTED', 'Sorting through collection relationships is not portable.');
  }
  return nestRelationships(resolved.relationships, resolved.field.name, order);
}
""".replace("__FILTERX_CASE_INSENSITIVE__", case_insensitive).replace(
    "__FILTERX_CASE_INSENSITIVE_SEARCH__",
    case_insensitive.replace("String(value)", "search"),
  )


def _render_security() -> str:
    return """// Generated by FilterX. Safe defaults; replace through backend.express.hooks_module.
import type { FilterxHooks } from './types.js';

export const hooks: FilterxHooks = {
  extractIdentity: () => null,
  rowPredicate: () => ({}),
  fieldVisible: () => true,
};
"""


def _render_router(max_query_cost: int, rate_limit: int) -> str:
    return f"""// Generated by FilterX. Do not edit.
import {{ Router, type NextFunction, type Request, type Response }} from 'express';
import ExcelJS from 'exceljs';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import {{ pinoHttp }} from 'pino-http';
import {{ ZodError }} from 'zod';
import {{ filterxMetadata }} from './metadata.js';
import {{ buildOrderBy, buildSearch, buildTree, combineWhere, FilterxQueryError, queryCost }} from './query.js';
import {{ filterBodySchema, paginationSchema }} from './validation.js';
import type {{ FilterBody, FilterCondition, FilterxErrorBody, FilterxHooks, IREntity }} from './types.js';

const DEFAULT_MAX_QUERY_COST = {max_query_cost};
const DEFAULT_RATE_LIMIT = {rate_limit};
const RESERVED_QUERY_KEYS = new Set(['page', 'size', 'sort_by', 'order', 'search']);
const URL_OPERATIONS = [
  'starts_with', 'ends_with', 'is_not_null', 'is_null', 'not_in', 'between',
  'ilike', 'like', 'gte', 'lte', 'in', 'ne', 'gt', 'lt', 'eq',
];

function errorBody(code: string, message: string, details?: unknown): FilterxErrorBody {{
  return {{ error: {{ code, message, ...(details === undefined ? {{}} : {{ details }}) }} }};
}}

function entityFor(name: string): IREntity {{
  const normalized = name.replace(/-/g, '').toLowerCase();
  const entity = filterxMetadata.entities.find((candidate) =>
    candidate.name.replace(/_/g, '').toLowerCase() === normalized ||
    `${{candidate.name.replace(/_/g, '').toLowerCase()}}s` === normalized,
  );
  if (!entity) throw new FilterxQueryError('ENTITY_UNKNOWN', `Unknown entity '${{name}}'.`);
  return entity;
}}

function delegateFor(prisma: Record<string, unknown>, entity: IREntity): any {{
  const name = entity.name.charAt(0).toLowerCase() + entity.name.slice(1);
  const delegate = prisma[name];
  if (!delegate) throw new FilterxQueryError('ENTITY_DELEGATE_MISSING', `Prisma delegate '${{name}}' is unavailable.`);
  return delegate;
}}

async function visibleMetadata(entity: IREntity, hooks: FilterxHooks, principal: unknown, request: Request, action: string) {{
  const fields = [];
  for (const field of entity.fields) {{
    if (await hooks.fieldVisible({{ principal, request, entity, field: field.name, action }})) fields.push(field);
  }}
  return {{ ...entity, fields }};
}}

async function projectRow(row: Record<string, unknown>, entity: IREntity, hooks: FilterxHooks, principal: unknown, request: Request, action: string) {{
  const projected: Record<string, unknown> = {{}};
  for (const field of entity.fields) {{
    if (await hooks.fieldVisible({{ principal, request, entity, field: field.name, action }})) projected[field.name] = row[field.name];
  }}
  for (const relationship of entity.relationships.filter((item) => !item.collection)) {{
    const related = row[relationship.name];
    if (!related || typeof related !== 'object') continue;
    const output: Record<string, unknown> = {{}};
    for (const [field, value] of Object.entries(related)) {{
      if (await hooks.fieldVisible({{ principal, request, entity, field: `${{relationship.name}}.${{field}}`, action }})) output[field] = value;
    }}
    if (Object.keys(output).length) projected[relationship.name] = output;
  }}
  return projected;
}}

function selectFor(entity: IREntity): Record<string, unknown> {{
  const select: Record<string, unknown> = Object.fromEntries(entity.fields.map((field) => [field.name, true]));
  for (const relationship of entity.relationships.filter((item) => !item.collection)) select[relationship.name] = true;
  return select;
}}

function exportValue(value: unknown): string | number | boolean {{
  if (value === null || value === undefined) return '';
  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') return value;
  if (value instanceof Date) return value.toISOString();
  return JSON.stringify(value);
}}

function csvCell(value: unknown): string {{
  const text = String(exportValue(value));
  return /[",\\r\\n]/.test(text) ? `"${{text.replace(/"/g, '""')}}"` : text;
}}

function urlFilters(query: Request['query']): FilterCondition[] {{
  const filters: FilterCondition[] = [];
  for (const [key, rawValue] of Object.entries(query)) {{
    if (RESERVED_QUERY_KEYS.has(key) || rawValue === '' || rawValue === undefined) continue;
    let field = key;
    let operation = 'eq';
    for (const candidate of URL_OPERATIONS) {{
      const suffix = `_${{candidate}}`;
      if (key.endsWith(suffix)) {{
        field = key.slice(0, -suffix.length);
        operation = candidate;
        break;
      }}
    }}
    if (!field) continue;
    const scalar = Array.isArray(rawValue) ? rawValue[0] : rawValue;
    const text = String(scalar);
    const value = ['in', 'not_in', 'between'].includes(operation)
      ? text.split(',').map((item) => item.trim())
      : text;
    filters.push({{ field, operation: operation as FilterCondition['operation'], value }});
  }}
  return filters;
}}

export function createFilterxRouter(prisma: Record<string, unknown>, hooks: FilterxHooks): Router {{
  const router = Router();
  router.use(helmet());
  router.use(pinoHttp());
  router.use(rateLimit({{
    windowMs: 60_000,
    limit: DEFAULT_RATE_LIMIT,
    standardHeaders: true,
    legacyHeaders: false,
    handler: (_request, response) => response.status(429).json(
      errorBody('RATE_LIMITED', 'Too many FilterX requests; retry after the rate-limit window.'),
    ),
  }}));

  router.use(async (request, response, next) => {{
    try {{ response.locals.filterxPrincipal = await hooks.extractIdentity(request); next(); }}
    catch (error) {{ next(error); }}
  }});

  router.get('/metadata', async (request, response, next) => {{
    try {{
      const principal = response.locals.filterxPrincipal;
      const entities = await Promise.all(filterxMetadata.entities.map((entity) => visibleMetadata(entity, hooks, principal, request, 'metadata.list')));
      response.json({{ entities, entity_count: entities.length }});
    }} catch (error) {{ next(error); }}
  }});

  router.get('/:entity/metadata', async (request, response, next) => {{
    try {{ response.json(await visibleMetadata(entityFor(String(request.params.entity)), hooks, response.locals.filterxPrincipal, request, 'metadata.read')); }}
    catch (error) {{ next(error); }}
  }});

  const executeQuery = async (request: Request, response: Response, next: NextFunction, body?: FilterBody) => {{
    try {{
      const entity = entityFor(String(request.params.entity));
      const delegate = delegateFor(prisma, entity);
      const page = paginationSchema.parse(request.query);
      const parsedBody = filterBodySchema.parse(body ?? {{ filters: [] }}) as FilterBody;
      const filters = body === undefined ? urlFilters(request.query) : (parsedBody.filters ?? []);
      const cost = queryCost(filters, parsedBody.filter_tree);
      if (cost > DEFAULT_MAX_QUERY_COST) throw new FilterxQueryError('QUERY_COST_EXCEEDED', `Query cost ${{cost}} exceeds limit ${{DEFAULT_MAX_QUERY_COST}}.`);
      const principal = response.locals.filterxPrincipal;
      const rowScope = await hooks.rowPredicate({{ principal, request, entity, action: body ? 'filter' : 'query' }});
      const where = combineWhere(
        rowScope ?? {{}},
        ...(filters.map((filter) => buildTree(entity, filterxMetadata.entities, filter))),
        buildTree(entity, filterxMetadata.entities, parsedBody.filter_tree),
        buildSearch(entity, page.search),
      );
      const [total, rows] = await Promise.all([
        delegate.count({{ where }}),
        delegate.findMany({{
          where,
          select: selectFor(entity),
          orderBy: buildOrderBy(entity, filterxMetadata.entities, page.sort_by, page.order),
          skip: (page.page - 1) * page.size,
          take: page.size,
        }}),
      ]);
      const data = await Promise.all(rows.map((row: Record<string, unknown>) => projectRow(row, entity, hooks, principal, request, body ? 'filter' : 'query')));
      response.json({{ data, meta: {{ page: page.page, size: page.size, total_items: total, total_pages: total ? Math.ceil(total / page.size) : 0 }} }});
    }} catch (error) {{ next(error); }}
  }};

  router.get('/:entity', (request, response, next) => executeQuery(request, response, next));
  router.get('/:entity/query', (request, response, next) => executeQuery(request, response, next));
  router.post('/:entity/filter', (request, response, next) => executeQuery(request, response, next, request.body));

  router.post('/:entity/export', async (request, response, next) => {{
    try {{
      const entity = entityFor(String(request.params.entity));
      const delegate = delegateFor(prisma, entity);
      const page = paginationSchema.parse(request.query);
      const parsedBody = filterBodySchema.parse(request.body ?? {{ filters: [] }}) as FilterBody;
      const filters = parsedBody.filters ?? [];
      const cost = queryCost(filters, parsedBody.filter_tree);
      if (cost > DEFAULT_MAX_QUERY_COST) throw new FilterxQueryError('QUERY_COST_EXCEEDED', `Query cost ${{cost}} exceeds limit ${{DEFAULT_MAX_QUERY_COST}}.`);
      const format = typeof request.query.format === 'string' ? request.query.format : 'csv';
      if (!['csv', 'xlsx', 'json'].includes(format)) throw new FilterxQueryError('EXPORT_FORMAT_UNSUPPORTED', `Unsupported export format '${{format}}'.`);
      const principal = response.locals.filterxPrincipal;
      const rowScope = await hooks.rowPredicate({{ principal, request, entity, action: 'export' }});
      const where = combineWhere(
        rowScope ?? {{}},
        ...(filters.map((filter) => buildTree(entity, filterxMetadata.entities, filter))),
        buildTree(entity, filterxMetadata.entities, parsedBody.filter_tree),
        buildSearch(entity, page.search),
      );
      const orderBy = buildOrderBy(entity, filterxMetadata.entities, page.sort_by, page.order);
      const batchSize = 250;
      let offset = 0;
      let headers: string[] = [];
      let firstJson = true;
      response.setHeader('Content-Disposition', `attachment; filename="${{entity.name.toLowerCase()}}.${{format}}"`);
      let workbook: ExcelJS.stream.xlsx.WorkbookWriter | undefined;
      let worksheet: any;
      if (format === 'csv') {{ response.type('text/csv; charset=utf-8'); response.write('\uFEFF'); }}
      else if (format === 'json') {{ response.type('application/json; charset=utf-8'); response.write('['); }}
      else {{
        response.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        workbook = new ExcelJS.stream.xlsx.WorkbookWriter({{ stream: response }});
        worksheet = workbook.addWorksheet('Export');
      }}
      while (true) {{
        const rows = await delegate.findMany({{ where, select: selectFor(entity), orderBy, skip: offset, take: batchSize }});
        if (!rows.length) break;
        const projected = await Promise.all(rows.map((row: Record<string, unknown>) => projectRow(row, entity, hooks, principal, request, 'export')));
        if (!headers.length && projected.length) {{
          headers = Object.keys(projected[0]);
          if (format === 'csv') response.write(`${{headers.map(csvCell).join(',')}}\\r\\n`);
          if (worksheet) worksheet.addRow(headers).commit();
        }}
        for (const row of projected) {{
          if (format === 'csv') response.write(`${{headers.map((field) => csvCell(row[field])).join(',')}}\\r\\n`);
          else if (format === 'json') {{ response.write(`${{firstJson ? '' : ','}}${{JSON.stringify(row)}}`); firstJson = false; }}
          else worksheet?.addRow(headers.map((field) => exportValue(row[field]))).commit();
        }}
        offset += rows.length;
        if (rows.length < batchSize) break;
      }}
      if (format === 'json') response.end(']');
      else if (format === 'csv') response.end();
      else {{ worksheet?.commit(); await workbook?.commit(); }}
    }} catch (error) {{ next(error); }}
  }});

  const executeGroup = async (request: Request, response: Response, next: NextFunction, body?: FilterBody) => {{
    try {{
      const entity = entityFor(String(request.params.entity));
      const groupField = String(request.params.field);
      if (groupField.includes('.')) throw new FilterxQueryError('GROUP_FIELD_UNSUPPORTED', 'Prisma relationship grouping is not portable.');
      const field = entity.fields.find((candidate) => candidate.name === groupField);
      if (!field) throw new FilterxQueryError('FIELD_UNKNOWN', `Unknown group field '${{groupField}}'.`);
      const delegate = delegateFor(prisma, entity);
      const principal = response.locals.filterxPrincipal;
      const parsedBody = filterBodySchema.parse(body ?? {{ filters: [] }}) as FilterBody;
      const filters = body === undefined ? urlFilters(request.query) : (parsedBody.filters ?? []);
      const cost = queryCost(filters, parsedBody.filter_tree);
      if (cost > DEFAULT_MAX_QUERY_COST) throw new FilterxQueryError('QUERY_COST_EXCEEDED', `Query cost ${{cost}} exceeds limit ${{DEFAULT_MAX_QUERY_COST}}.`);
      const action = body === undefined ? 'group' : 'group.filter';
      if (!(await hooks.fieldVisible({{ principal, request, entity, field: field.name, action }})))
        throw new FilterxQueryError('FIELD_FORBIDDEN', `Grouping by field '${{field.name}}' is not permitted.`);
      const rowScope = await hooks.rowPredicate({{ principal, request, entity, action }});
      const search = typeof request.query.search === 'string' ? request.query.search : undefined;
      const where = combineWhere(
        rowScope ?? {{}},
        ...(filters.map((filter) => buildTree(entity, filterxMetadata.entities, filter))),
        buildTree(entity, filterxMetadata.entities, parsedBody.filter_tree),
        buildSearch(entity, search),
      );
      const rows = await delegate.groupBy({{ by: [field.name], where, _count: {{ _all: true }} }});
      response.json(rows.map((row: any) => ({{ key: row[field.name], count: row._count._all }})));
    }} catch (error) {{ next(error); }}
  }};

  router.get('/:entity/group-by/:field', (request, response, next) => executeGroup(request, response, next));
  router.post('/:entity/group-by/:field/filter', (request, response, next) => executeGroup(request, response, next, request.body));

  router.use((error: unknown, _request: Request, response: Response, _next: NextFunction) => {{
    if (error instanceof FilterxQueryError) return response.status(400).json(errorBody(error.code, error.message, error.details));
    if (error instanceof ZodError) return response.status(400).json(errorBody('VALIDATION_ERROR', 'Request validation failed.', error.issues));
    const message = error instanceof Error ? error.message : 'Unexpected FilterX error.';
    return response.status(500).json(errorBody('INTERNAL_ERROR', message));
  }});
  return router;
}}
"""


def _render_index(custom_hooks_import: str | None) -> str:
    hook_import = custom_hooks_import or "./security.js"
    return f"""// Generated by FilterX. Do not edit.
import {{ PrismaClient }} from '@prisma/client';
import {{ createFilterxRouter }} from './router.js';
import {{ hooks }} from '{hook_import}';

export const filterxPrisma = new PrismaClient();
export const filterxRouter = createFilterxRouter(filterxPrisma as unknown as Record<string, unknown>, hooks);
export {{ createFilterxRouter }} from './router.js';
export {{ filterxMetadata }} from './metadata.js';
export type * from './types.js';
"""


class ExpressPrismaRenderer:
    name = "express-prisma"
    version = "1.0.0"
    target = RendererTarget.BACKEND

    def _load(self, args: Any) -> tuple[Path, dict[str, Any], FilterxIR]:
        project_root = Path(args.project_root).resolve()
        config_path = Path(args.config).resolve() if args.config else None
        cfg = load_effective_config(project_root, config_path).raw
        ir_path = project_root / cfg["output"].get("ir_file", ".filterx/ir.json")
        if not ir_path.exists():
            raise ValueError(f"FilterX IR artifact is missing at '{ir_path}'. Run 'filterx scan' first.")
        return project_root, cfg, ir_from_dict(load_json(ir_path))

    def _app_file(self, project_root: Path, express: dict[str, Any]) -> Path:
        configured = project_root / str(express.get("app_file", "src/app.ts"))
        if configured.exists():
            return configured
        candidates = [project_root / name for name in ("src/app.ts", "src/server.ts", "src/index.ts")]
        existing = [path for path in candidates if path.exists()]
        if len(existing) == 1:
            return existing[0]
        if not existing:
            raise ValueError("Express application entry file was not found. Set backend.express.app_file explicitly.")
        raise ValueError(
            "Multiple Express application entry files were detected. Set backend.express.app_file explicitly: "
            + ", ".join(str(path.relative_to(project_root)) for path in existing)
        )

    def _prisma_provider(self, project_root: Path, cfg: dict[str, Any]) -> str:
        schema_path = project_root / str(cfg.get("scan", {}).get("prisma", {}).get("schema", "prisma/schema.prisma"))
        if not schema_path.exists():
            raise ValueError(f"Prisma schema was not found at '{schema_path}'.")
        source = schema_path.read_text(encoding="utf-8")
        datasource = re.search(r"datasource\s+\w+\s*\{(?P<body>.*?)\}", source, re.DOTALL)
        provider = re.search(r'provider\s*=\s*"(?P<name>[^"]+)"', datasource.group("body") if datasource else "")
        if not provider:
            raise ValueError(f"Prisma datasource provider could not be determined from '{schema_path}'.")
        return provider.group("name").lower()

    def install(self, args: Any) -> int:
        try:
            project_root, cfg, ir = self._load(args)
            express = dict(cfg["backend"].get("express", {}))
            app_file = self._app_file(project_root, express)
            prisma_provider = self._prisma_provider(project_root, cfg)
        except ValueError as exc:
            print(json.dumps({"errors": [{"code": "EXPRESS_CONFIGURATION_INVALID", "message": str(exc)}]}, indent=2))
            return 2

        generated_root = Path(str(express.get("generated_root", "src/filterx-generated")))
        package_file = str(express.get("package_json", "package.json"))
        tsconfig = str(express.get("tsconfig", "tsconfig.json"))
        node_next = _node_next(project_root, tsconfig)
        custom_hooks = express.get("hooks_module")
        source_extension = ".js" if node_next else ""
        mount_import = _ts_import(app_file, project_root / generated_root / "index", node_next=node_next)
        mount_snippet = (
            f"import {{ filterxRouter }} from '{mount_import}';\n"
            f"app.use('{str(cfg['backend'].get('api_prefix', '/api')).rstrip('/')}/filterx', filterxRouter);"
        )
        files = {
            "types.ts": _render_types(),
            "metadata.ts": _render_metadata(ir).replace("'./types.js'", f"'./types{source_extension}'"),
            "validation.ts": _render_validation(),
            "query.ts": _render_query(prisma_provider),
            "security.ts": _render_security(),
            "router.ts": _render_router(
                int(express.get("max_query_cost", 100)),
                int(express.get("rate_limit_per_minute", 120)),
            ),
            "index.ts": _render_index(str(custom_hooks) if custom_hooks else None),
        }
        if not node_next:
            files = {name: content.replace(".js'", "'") for name, content in files.items()}
        operations = [
            PatchOp(kind="generated_file", path=(generated_root / name).as_posix(), content=content)
            for name, content in files.items()
        ]
        operations.append(
            PatchOp(
                kind="structured_merge",
                path=package_file,
                owner="host",
                structured_format="json",
                merge={
                    "dependencies": {
                        "@prisma/client": "^6.0.0",
                        "exceljs": "^4.4.0",
                        "express": "^5.0.0",
                        "express-rate-limit": "^7.5.0",
                        "helmet": "^8.0.0",
                        "pino": "^9.0.0",
                        "pino-http": "^10.0.0",
                        "zod": "^3.24.0",
                    },
                    "devDependencies": {
                        "@types/express": "^5.0.0",
                        "prisma": "^6.0.0",
                        "typescript": "^5.7.0",
                    },
                },
            )
        )
        operations.append(
            PatchOp(
                kind="anchor_insert",
                path=app_file.relative_to(project_root).as_posix(),
                anchor=str(express.get("app_anchor", "// FILTERX:ROUTER_MOUNT")),
                snippet=mount_snippet,
                owner="host",
            )
        )
        result = apply_patch_operations(
            project_root=project_root,
            operations=operations,
            manifest_path=project_root / cfg["safety"]["idempotency_manifest"],
            patch_dir=project_root / cfg["output"]["patch_dir"],
            dry_run=bool(getattr(args, "dry_run", False)),
            check_mode=bool(getattr(args, "check", False)),
            strict_conflict_mode=bool(cfg["safety"].get("strict_conflict_mode", True)),
            description="backend.install.express-prisma",
        )
        payload = {
            "dry_run": result.dry_run,
            "patch_id": result.patch_id,
            "framework": self.name,
            "applied_ops": result.applied_ops,
            "skipped_ops": result.skipped_ops,
            "touched_files": result.touched_files,
            "issues": [{"code": item.code, "message": item.message, "context": item.context} for item in result.issues],
        }
        print(json.dumps(payload, indent=2))
        return 3 if result.has_conflicts else 0

    def validate(self, args: Any) -> int:
        try:
            project_root, cfg, _ir = self._load(args)
            express = dict(cfg["backend"].get("express", {}))
            app_file = self._app_file(project_root, express)
        except ValueError as exc:
            print(json.dumps({"errors": [{"code": "EXPRESS_CONFIGURATION_INVALID", "message": str(exc)}]}, indent=2))
            return 4
        generated_root = project_root / str(express.get("generated_root", "src/filterx-generated"))
        required = ("types.ts", "metadata.ts", "validation.ts", "query.ts", "security.ts", "router.ts", "index.ts")
        errors = [
            {"code": "EXPRESS_GENERATED_FILE_MISSING", "path": str(generated_root / name)}
            for name in required
            if not (generated_root / name).exists()
        ]
        anchor = str(express.get("app_anchor", "// FILTERX:ROUTER_MOUNT"))
        if anchor not in app_file.read_text(encoding="utf-8"):
            errors.append({"code": "EXPRESS_MOUNT_ANCHOR_MISSING", "path": str(app_file), "anchor": anchor})
        payload = {"errors": errors, "warnings": [], "error_count": len(errors), "warning_count": 0}
        print(json.dumps(payload, indent=2))
        return 4 if errors else 0

    def remove(self, args: Any) -> int:
        print(json.dumps({"errors": [{"code": "EXPRESS_REMOVE_USE_ROLLBACK", "message": "Use filterx rollback with the Express install patch id."}]}, indent=2))
        return 2
