from __future__ import annotations

import json
import os
import re
import subprocess
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

from filterx.core.config import load_effective_config
from filterx.core.io import load_json
from filterx.core.ir import FilterxIR, ir_from_dict
from filterx.core.patcher import PatchOp, apply_patch_operations

from .base import RendererTarget


_JAVA_PACKAGE_RE = re.compile(r"^[a-zA-Z_$][\w$]*(?:\.[a-zA-Z_$][\w$]*)*$")
_BOOT_APPLICATION_RE = re.compile(r"@SpringBootApplication\b")
_PACKAGE_RE = re.compile(r"^\s*package\s+([\w.$]+)\s*;", re.MULTILINE)
_BOOT_PLUGIN_RE = re.compile(r"(?:org\.springframework\.boot[^\n]*?version\s*[=( ]\s*['\"])(\d+(?:\.\d+){1,2})")


@dataclass(frozen=True)
class SpringLayout:
    module_root: Path
    source_root: Path
    generated_package: str
    generated_root: Path
    application_class: str
    build_tool: str
    manifest: Path
    command: str


def _java_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _package_header(package: str) -> str:
    return f"// Generated by FilterX. Do not edit.\npackage {package};\n\n"


def _render_metadata(package: str, ir: FilterxIR) -> str:
    payload = json.dumps(ir.to_dict(), separators=(",", ":"), ensure_ascii=True)
    return _package_header(package) + f'''import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import org.springframework.stereotype.Component;

@Component
public final class FilterxMetadata {{
    public static final String IR_VERSION = "filterx-ir/v1";
    private static final String IR_JSON = {_java_string(payload)};
    private final JsonNode root;

    public FilterxMetadata(ObjectMapper mapper) {{
        try {{
            this.root = mapper.readTree(IR_JSON);
        }} catch (Exception error) {{
            throw new IllegalStateException("Generated FilterX IR is invalid", error);
        }}
        if (!IR_VERSION.equals(root.path("version").asText())) {{
            throw new IllegalStateException("Unsupported generated FilterX IR version: " + root.path("version").asText());
        }}
    }}

    public JsonNode root() {{ return root; }}

    public JsonNode entity(String requested) {{
        String normalized = requested.replace("-", "").replace("_", "").toLowerCase();
        for (JsonNode entity : root.path("entities")) {{
            String name = entity.path("name").asText();
            String candidate = name.replace("_", "").toLowerCase();
            if (candidate.equals(normalized) || (candidate + "s").equals(normalized)) return entity;
        }}
        throw new FilterxRequestException("ENTITY_UNKNOWN", "Unknown entity '" + requested + "'.");
    }}

    public Class<Object> entityClass(JsonNode entity) {{
        String type = entity.path("identity").path("module").asText() + "." + entity.path("name").asText();
        try {{
            @SuppressWarnings("unchecked") Class<Object> loaded = (Class<Object>) Class.forName(type);
            return loaded;
        }} catch (ClassNotFoundException error) {{
            throw new FilterxRequestException("ENTITY_CLASS_MISSING", "JPA entity class '" + type + "' is unavailable.");
        }}
    }}

    public List<String> fieldNames(JsonNode entity) {{
        List<String> names = new ArrayList<>();
        entity.path("fields").forEach(field -> names.add(field.path("name").asText()));
        return List.copyOf(names);
    }}

    public JsonNode field(JsonNode entity, String path) {{
        String[] parts = path.split("\\\\.");
        JsonNode current = entity;
        for (int index = 0; index < parts.length - 1; index++) {{
            JsonNode relationship = null;
            for (JsonNode candidate : current.path("relationships")) {{
                if (parts[index].equals(candidate.path("name").asText())) {{ relationship = candidate; break; }}
            }}
            if (relationship == null) throw new FilterxRequestException("RELATIONSHIP_UNKNOWN", "Unknown relationship '" + parts[index] + "' in '" + path + "'.");
            current = entity(relationship.path("target_entity").asText());
        }}
        String leaf = parts[parts.length - 1];
        for (JsonNode field : current.path("fields")) if (leaf.equals(field.path("name").asText())) return field;
        throw new FilterxRequestException("FIELD_UNKNOWN", "Unknown field '" + path + "'.");
    }}
}}
'''


def _java_type(source_type: str) -> str:
    source = source_type.strip()
    allowed = {
        "java.lang.String": "String", "String": "String",
        "java.lang.Integer": "Integer", "int": "Integer",
        "java.lang.Long": "Long", "long": "Long",
        "java.lang.Double": "Double", "double": "Double",
        "java.lang.Float": "Float", "float": "Float",
        "java.lang.Boolean": "Boolean", "boolean": "Boolean",
        "java.math.BigDecimal": "java.math.BigDecimal",
        "java.time.LocalDate": "java.time.LocalDate",
        "java.time.LocalDateTime": "java.time.LocalDateTime",
        "java.time.OffsetDateTime": "java.time.OffsetDateTime",
        "java.time.Instant": "java.time.Instant",
        "java.util.UUID": "java.util.UUID",
    }
    return allowed.get(source, "Object")


def _render_dtos(package: str, ir: FilterxIR) -> str:
    records: list[str] = []
    for entity in ir.entities:
        components = ", ".join(f"{_java_type(field.source_type)} {field.name}" for field in entity.fields)
        records.append(f"    public record {entity.name}Dto({components}) {{}}")
    body = "\n\n".join(records) or "    public record EmptyDto() {}"
    return _package_header(package) + f'''/** Flat, relationship-free response records. They never serialize JPA associations. */
public final class FilterxDtos {{
    private FilterxDtos() {{}}

{body}
}}
'''


def _render_requests(package: str) -> str:
    return _package_header(package) + '''import com.fasterxml.jackson.databind.JsonNode;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import java.util.List;

public final class FilterxRequests {
    private FilterxRequests() {}

    public record FilterCondition(
        @NotBlank String field,
        @NotBlank String operation,
        JsonNode value
    ) {}

    public record FilterNode(
        String node_type,
        String operator,
        String field,
        String operation,
        JsonNode value,
        List<@Valid FilterNode> children
    ) {
        public FilterCondition condition() {
            return field == null && operation == null ? null : new FilterCondition(field, operation, value);
        }
    }

    public record FilterRequest(
        List<@Valid FilterCondition> filters,
        @Valid FilterNode filter_tree
    ) {
        public FilterRequest {
            filters = filters == null ? List.of() : List.copyOf(filters);
        }
    }

    public record PageMeta(int page, int size, long total_items, int total_pages) {}
    public record PageResponse(List<java.util.Map<String, Object>> data, PageMeta meta) {}
    public record GroupResult(Object key, long count) {}
}
'''


def _render_security(package: str) -> str:
    return _package_header(package) + '''import com.fasterxml.jackson.databind.JsonNode;
import jakarta.servlet.http.HttpServletRequest;
import java.io.IOException;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletResponse;

public final class FilterxSecurity {
    private FilterxSecurity() {}

    public interface IdentityExtractor {
        Object extract(HttpServletRequest request);
    }

    public interface RowLevelSecurity {
        Specification<Object> specification(Object principal, JsonNode entity, String action, HttpServletRequest request);
    }

    public interface FieldVisibility {
        boolean visible(Object principal, JsonNode entity, String field, String action, HttpServletRequest request);
    }

    public static final class IdentityFilter extends OncePerRequestFilter {
        public static final String PRINCIPAL_ATTRIBUTE = "filterx.principal";
        private final IdentityExtractor extractor;
        public IdentityFilter(IdentityExtractor extractor) { this.extractor = extractor; }
        @Override protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain)
                throws ServletException, IOException {
            request.setAttribute(PRINCIPAL_ATTRIBUTE, extractor.extract(request));
            chain.doFilter(request, response);
        }
    }

    @Component("filterxAuthorization")
    public static final class Authorization {
        public boolean authorize(Authentication authentication, String entity, String action) {
            return true;
        }
    }
}
'''


def _render_specifications(package: str) -> str:
    return _package_header(package) + '''import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.Expression;
import jakarta.persistence.criteria.From;
import jakarta.persistence.criteria.JoinType;
import jakarta.persistence.criteria.Path;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.UUID;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Component;

@Component
public final class FilterxSpecifications {
    private final FilterxMetadata metadata;
    public FilterxSpecifications(FilterxMetadata metadata) { this.metadata = metadata; }

    public Specification<Object> condition(JsonNode entity, FilterxRequests.FilterCondition condition) {
        JsonNode field = metadata.field(entity, condition.field());
        boolean supported = false;
        for (JsonNode operation : field.path("operations")) if (condition.operation().equals(operation.asText())) supported = true;
        if (!supported) throw new FilterxRequestException("OPERATION_UNSUPPORTED", "Operation '" + condition.operation() + "' is not valid for '" + condition.field() + "'.");
        return (root, query, cb) -> predicate(root, cb, condition);
    }

    public Specification<Object> tree(JsonNode entity, FilterxRequests.FilterNode node) {
        if (node == null) return Specification.where(null);
        if (node.condition() != null) return condition(entity, node.condition());
        List<FilterxRequests.FilterNode> children = node.children() == null ? List.of() : node.children();
        if (children.isEmpty()) throw new FilterxRequestException("FILTER_TREE_INVALID", "Filter groups require at least one child.");
        Specification<Object> combined = tree(entity, children.get(0));
        for (int index = 1; index < children.size(); index++) {
            combined = "OR".equalsIgnoreCase(node.operator()) ? combined.or(tree(entity, children.get(index))) : combined.and(tree(entity, children.get(index)));
        }
        return combined;
    }

    public Specification<Object> search(JsonNode entity, String search) {
        if (search == null || search.isBlank()) return Specification.where(null);
        return (root, query, cb) -> {
            List<Predicate> predicates = new ArrayList<>();
            for (JsonNode field : entity.path("fields")) {
                if (!"string".equals(field.path("type").asText())) continue;
                predicates.add(cb.like(cb.lower(root.get(field.path("name").asText()).as(String.class)), "%" + escape(search.toLowerCase(Locale.ROOT)) + "%", '\\\\'));
            }
            return predicates.isEmpty() ? cb.conjunction() : cb.or(predicates.toArray(Predicate[]::new));
        };
    }

    public Specification<Object> softDelete(JsonNode entity) {
        JsonNode softDelete = entity.path("soft_delete");
        if (!softDelete.path("respected").asBoolean() || softDelete.path("field").isNull()) return Specification.where(null);
        String field = softDelete.path("field").asText();
        return (root, query, cb) -> field.toLowerCase(Locale.ROOT).contains("deleted") && root.get(field).getJavaType() == Boolean.class
            ? cb.isFalse(root.get(field)) : cb.isNull(root.get(field));
    }

    private Predicate predicate(Root<Object> root, CriteriaBuilder cb, FilterxRequests.FilterCondition condition) {
        Path<?> path = resolve(root, condition.field());
        Object value = List.of("in", "not_in", "between", "is_null", "is_not_null").contains(condition.operation())
            ? null : coerce(path.getJavaType(), condition.value());
        return switch (condition.operation()) {
            case "eq" -> value == null ? cb.isNull(path) : cb.equal(path, value);
            case "ne" -> value == null ? cb.isNotNull(path) : cb.notEqual(path, value);
            case "gt" -> compare(cb, path, value, "gt");
            case "gte" -> compare(cb, path, value, "gte");
            case "lt" -> compare(cb, path, value, "lt");
            case "lte" -> compare(cb, path, value, "lte");
            case "in", "not_in" -> membership(cb, path, condition.value(), "not_in".equals(condition.operation()));
            case "between" -> between(cb, path, condition.value());
            case "is_null" -> cb.isNull(path);
            case "is_not_null" -> cb.isNotNull(path);
            case "like" -> cb.like(path.as(String.class), "%" + escape(String.valueOf(value)) + "%", '\\\\');
            case "ilike" -> cb.like(cb.lower(path.as(String.class)), "%" + escape(String.valueOf(value).toLowerCase(Locale.ROOT)) + "%", '\\\\');
            case "starts_with" -> cb.like(path.as(String.class), escape(String.valueOf(value)) + "%", '\\\\');
            case "ends_with" -> cb.like(path.as(String.class), "%" + escape(String.valueOf(value)), '\\\\');
            default -> throw new FilterxRequestException("OPERATION_UNSUPPORTED", "Unsupported operation '" + condition.operation() + "'.");
        };
    }

    private Path<?> resolve(Root<Object> root, String field) {
        String[] parts = field.split("\\\\.");
        From<?, ?> from = root;
        for (int index = 0; index < parts.length - 1; index++) from = from.join(parts[index], JoinType.LEFT);
        return from.get(parts[parts.length - 1]);
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    private Predicate compare(CriteriaBuilder cb, Path<?> path, Object value, String operation) {
        if (!(value instanceof Comparable comparable)) throw new FilterxRequestException("VALUE_INVALID", "Comparison requires a comparable value.");
        Expression<? extends Comparable> expression = path.as((Class<? extends Comparable>) value.getClass());
        return switch (operation) {
            case "gt" -> cb.greaterThan(expression, comparable);
            case "gte" -> cb.greaterThanOrEqualTo(expression, comparable);
            case "lt" -> cb.lessThan(expression, comparable);
            default -> cb.lessThanOrEqualTo(expression, comparable);
        };
    }

    private Predicate membership(CriteriaBuilder cb, Path<?> path, JsonNode value, boolean negate) {
        if (value == null || !value.isArray()) throw new FilterxRequestException("VALUE_INVALID", "Membership operations require an array.");
        CriteriaBuilder.In<Object> clause = cb.in(path);
        value.forEach(item -> clause.value(coerce(path.getJavaType(), item)));
        return negate ? cb.not(clause) : clause;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    private Predicate between(CriteriaBuilder cb, Path<?> path, JsonNode value) {
        if (value == null || !value.isArray() || value.size() != 2) throw new FilterxRequestException("VALUE_INVALID", "between requires exactly two values.");
        Comparable first = (Comparable) coerce(path.getJavaType(), value.get(0));
        Comparable second = (Comparable) coerce(path.getJavaType(), value.get(1));
        return cb.between((Expression<? extends Comparable>) path, first, second);
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private Object coerce(Class<?> type, JsonNode value) {
        if (value == null || value.isNull()) return null;
        String text = value.asText();
        try {
            if (type == String.class) return text;
            if (type == Integer.class || type == int.class) return Integer.valueOf(text);
            if (type == Long.class || type == long.class) return Long.valueOf(text);
            if (type == Double.class || type == double.class) return Double.valueOf(text);
            if (type == Float.class || type == float.class) return Float.valueOf(text);
            if (type == BigDecimal.class) return new BigDecimal(text);
            if (type == Boolean.class || type == boolean.class) return Boolean.valueOf(text);
            if (type == UUID.class) return UUID.fromString(text);
            if (type == LocalDate.class) return LocalDate.parse(text);
            if (type == LocalDateTime.class) return LocalDateTime.parse(text);
            if (type == OffsetDateTime.class) return OffsetDateTime.parse(text);
            if (type == Instant.class) return Instant.parse(text);
            if (type.isEnum()) return Enum.valueOf((Class<Enum>) type, text);
            return text;
        } catch (RuntimeException error) {
            throw new FilterxRequestException("VALUE_INVALID", "Value '" + text + "' is invalid for " + type.getSimpleName() + ".");
        }
    }

    private String escape(String value) { return value.replace("\\\\", "\\\\\\\\").replace("%", "\\\\%").replace("_", "\\\\_"); }
}
'''


def _render_query_service(package: str, max_cost: int) -> str:
    return _package_header(package) + f'''import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Tuple;
import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Order;
import jakarta.persistence.criteria.Path;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;
import jakarta.servlet.http.HttpServletRequest;
import java.beans.PropertyDescriptor;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.BeanWrapperImpl;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class FilterxQueryService {{
    private static final Logger LOG = LoggerFactory.getLogger(FilterxQueryService.class);
    private static final int MAX_QUERY_COST = {max_cost};
    private final EntityManager entityManager;
    private final FilterxMetadata metadata;
    private final FilterxSpecifications specifications;
    private final FilterxSecurity.RowLevelSecurity rowSecurity;
    private final FilterxSecurity.FieldVisibility visibility;

    public FilterxQueryService(EntityManager entityManager, FilterxMetadata metadata, FilterxSpecifications specifications,
            FilterxSecurity.RowLevelSecurity rowSecurity, FilterxSecurity.FieldVisibility visibility) {{
        this.entityManager = entityManager;
        this.metadata = metadata;
        this.specifications = specifications;
        this.rowSecurity = rowSecurity;
        this.visibility = visibility;
    }}

    @Transactional(readOnly = true)
    public FilterxRequests.PageResponse query(String requested, FilterxRequests.FilterRequest request, int page, int size,
            String sortBy, String order, String search, String action, HttpServletRequest servletRequest) {{
        JsonNode entity = metadata.entity(requested);
        guardCost(request);
        Object principal = servletRequest.getAttribute(FilterxSecurity.IdentityFilter.PRINCIPAL_ATTRIBUTE);
        Specification<Object> specification = compose(entity, request, search, principal, action, servletRequest);
        Class<Object> type = metadata.entityClass(entity);
        CriteriaBuilder cb = entityManager.getCriteriaBuilder();
        CriteriaQuery<Object> query = cb.createQuery(Object.class);
        Root<Object> root = query.from(type);
        Predicate predicate = specification.toPredicate(root, query, cb);
        query.select(root).where(predicate == null ? cb.conjunction() : predicate).distinct(true);
        query.orderBy(sort(cb, root, entity, sortBy, order));
        List<Object> rows = entityManager.createQuery(query).setFirstResult((page - 1) * size).setMaxResults(size).getResultList();

        CriteriaQuery<Long> countQuery = cb.createQuery(Long.class);
        Root<Object> countRoot = countQuery.from(type);
        Predicate countPredicate = specification.toPredicate(countRoot, countQuery, cb);
        countQuery.select(cb.countDistinct(countRoot)).where(countPredicate == null ? cb.conjunction() : countPredicate);
        long total = entityManager.createQuery(countQuery).getSingleResult();
        List<Map<String, Object>> data = rows.stream().map(row -> project(row, entity, principal, action, servletRequest)).toList();
        int totalPages = total == 0 ? 0 : (int) Math.ceil((double) total / size);
        LOG.info("filterx_query entity={{}} action={{}} page={{}} size={{}} total={{}}", entity.path("name").asText(), action, page, size, total);
        return new FilterxRequests.PageResponse(data, new FilterxRequests.PageMeta(page, size, total, totalPages));
    }}

    @Transactional(readOnly = true)
    public List<FilterxRequests.GroupResult> group(String requested, String groupField, FilterxRequests.FilterRequest request,
            String search, String action, HttpServletRequest servletRequest) {{
        if (groupField.contains(".")) throw new FilterxRequestException("GROUP_FIELD_UNSUPPORTED", "Relationship grouping is not portable.");
        JsonNode entity = metadata.entity(requested);
        metadata.field(entity, groupField);
        guardCost(request);
        Object principal = servletRequest.getAttribute(FilterxSecurity.IdentityFilter.PRINCIPAL_ATTRIBUTE);
        Specification<Object> specification = compose(entity, request, search, principal, action, servletRequest);
        CriteriaBuilder cb = entityManager.getCriteriaBuilder();
        CriteriaQuery<Tuple> query = cb.createTupleQuery();
        Root<Object> root = query.from(metadata.entityClass(entity));
        Path<?> group = root.get(groupField);
        Predicate predicate = specification.toPredicate(root, query, cb);
        query.multiselect(group.alias("key"), cb.count(root).alias("count")).where(predicate == null ? cb.conjunction() : predicate).groupBy(group);
        return entityManager.createQuery(query).getResultList().stream()
            .map(tuple -> new FilterxRequests.GroupResult(tuple.get("key"), ((Number) tuple.get("count")).longValue())).toList();
    }}

    private Specification<Object> compose(JsonNode entity, FilterxRequests.FilterRequest request, String search,
            Object principal, String action, HttpServletRequest servletRequest) {{
        Specification<Object> result = specifications.softDelete(entity).and(specifications.search(entity, search));
        for (FilterxRequests.FilterCondition condition : request.filters()) result = result.and(specifications.condition(entity, condition));
        result = result.and(specifications.tree(entity, request.filter_tree()));
        Specification<Object> security = rowSecurity.specification(principal, entity, action, servletRequest);
        return security == null ? result : result.and(security);
    }}

    private Order sort(CriteriaBuilder cb, Root<Object> root, JsonNode entity, String sortBy, String direction) {{
        String selected = sortBy == null || sortBy.isBlank() ? entity.path("identity").path("primary_keys").path(0).asText() : sortBy;
        if (selected.isBlank()) selected = entity.path("fields").path(0).path("name").asText();
        metadata.field(entity, selected);
        Path<?> path = root;
        for (String part : selected.split("\\\\.")) path = path.get(part);
        return "desc".equalsIgnoreCase(direction) ? cb.desc(path) : cb.asc(path);
    }}

    private Map<String, Object> project(Object row, JsonNode entity, Object principal, String action, HttpServletRequest request) {{
        BeanWrapperImpl wrapper = new BeanWrapperImpl(row);
        Map<String, Object> projected = new LinkedHashMap<>();
        for (String field : metadata.fieldNames(entity)) {{
            if (!visibility.visible(principal, entity, field, action, request) || !wrapper.isReadableProperty(field)) continue;
            projected.put(field, wrapper.getPropertyValue(field));
        }}
        return projected;
    }}

    private void guardCost(FilterxRequests.FilterRequest request) {{
        int cost = request.filters().stream().mapToInt(condition -> 1 + condition.field().split("\\\\.").length).sum() + treeCost(request.filter_tree(), 1);
        if (cost > MAX_QUERY_COST) throw new FilterxRequestException("QUERY_COST_EXCEEDED", "Query cost " + cost + " exceeds limit " + MAX_QUERY_COST + ".");
    }}

    private int treeCost(FilterxRequests.FilterNode node, int depth) {{
        if (node == null) return 0;
        if (node.condition() != null) return depth + node.condition().field().split("\\\\.").length;
        return depth + (node.children() == null ? 0 : node.children().stream().mapToInt(child -> treeCost(child, depth + 1)).sum());
    }}
}}
'''


def _render_controller(package: str, api_prefix: str) -> str:
    route = api_prefix.rstrip("/") + "/filterx"
    return _package_header(package) + f'''import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.springframework.http.ContentDisposition;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody;

@RestController
@RequestMapping({_java_string(route)})
@Validated
public class FilterxController {{
    private static final List<String> OPERATIONS = List.of("starts_with", "ends_with", "is_not_null", "is_null", "not_in", "between", "ilike", "like", "gte", "lte", "in", "ne", "gt", "lt", "eq");
    private final FilterxQueryService queries;
    private final FilterxMetadata metadata;
    private final FilterxSecurity.FieldVisibility visibility;
    private final FilterxExportService exports;

    public FilterxController(FilterxQueryService queries, FilterxMetadata metadata, FilterxSecurity.FieldVisibility visibility,
            FilterxExportService exports) {{
        this.queries = queries; this.metadata = metadata; this.visibility = visibility; this.exports = exports;
    }}

    @GetMapping("/metadata")
    @PreAuthorize("@filterxAuthorization.authorize(authentication, 'all', 'metadata.list')")
    public Map<String, Object> metadata(HttpServletRequest request) {{
        List<Object> entities = new ArrayList<>();
        metadata.root().path("entities").forEach(entity -> entities.add(visibleMetadata(entity, "metadata.list", request)));
        return Map.of("entities", entities, "entity_count", entities.size());
    }}

    @GetMapping("/{{entity}}/metadata")
    @PreAuthorize("@filterxAuthorization.authorize(authentication, #entity, 'metadata.read')")
    public Object entityMetadata(@PathVariable String entity, HttpServletRequest request) {{
        return visibleMetadata(metadata.entity(entity), "metadata.read", request);
    }}

    @GetMapping({{"/{{entity}}", "/{{entity}}/query"}})
    @PreAuthorize("@filterxAuthorization.authorize(authentication, #entity, 'query')")
    public FilterxRequests.PageResponse query(@PathVariable String entity, @RequestParam Map<String, String> parameters,
            @RequestParam(defaultValue = "1") @Min(1) int page, @RequestParam(defaultValue = "20") @Min(1) @Max(100) int size,
            @RequestParam(required = false, name = "sort_by") String sortBy, @RequestParam(defaultValue = "asc") String order,
            @RequestParam(required = false) String search, HttpServletRequest request) {{
        return queries.query(entity, fromParameters(parameters), page, size, sortBy, order, search, "query", request);
    }}

    @PostMapping("/{{entity}}/filter")
    @PreAuthorize("@filterxAuthorization.authorize(authentication, #entity, 'filter')")
    public FilterxRequests.PageResponse filter(@PathVariable String entity, @Valid @RequestBody FilterxRequests.FilterRequest body,
            @RequestParam(defaultValue = "1") @Min(1) int page, @RequestParam(defaultValue = "20") @Min(1) @Max(100) int size,
            @RequestParam(required = false, name = "sort_by") String sortBy, @RequestParam(defaultValue = "asc") String order,
            @RequestParam(required = false) String search, HttpServletRequest request) {{
        return queries.query(entity, body, page, size, sortBy, order, search, "filter", request);
    }}

    @PostMapping("/{{entity}}/export")
    @PreAuthorize("@filterxAuthorization.authorize(authentication, #entity, 'export')")
    public ResponseEntity<StreamingResponseBody> export(@PathVariable String entity,
            @Valid @RequestBody(required = false) FilterxRequests.FilterRequest body,
            @RequestParam(defaultValue = "csv") String format,
            @RequestParam(required = false, name = "sort_by") String sortBy,
            @RequestParam(defaultValue = "asc") String order,
            @RequestParam(required = false) String search, HttpServletRequest request) {{
        String normalized = format.toLowerCase(java.util.Locale.ROOT);
        if (!List.of("csv", "xlsx", "json").contains(normalized)) throw new FilterxRequestException("EXPORT_FORMAT_UNSUPPORTED", "Unsupported export format '" + format + "'.");
        FilterxRequests.FilterRequest filters = body == null ? new FilterxRequests.FilterRequest(List.of(), null) : body;
        MediaType type = switch (normalized) {{
            case "csv" -> MediaType.parseMediaType("text/csv;charset=UTF-8");
            case "xlsx" -> MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            default -> MediaType.APPLICATION_JSON;
        }};
        StreamingResponseBody stream = output -> exports.write(entity, filters, sortBy, order, search, normalized, request, output);
        HttpHeaders headers = new HttpHeaders();
        headers.setContentDisposition(ContentDisposition.attachment().filename(entity + "." + normalized).build());
        return ResponseEntity.ok().headers(headers).contentType(type).body(stream);
    }}

    @GetMapping("/{{entity}}/group-by/{{field}}")
    @PreAuthorize("@filterxAuthorization.authorize(authentication, #entity, 'group')")
    public List<FilterxRequests.GroupResult> group(@PathVariable String entity, @PathVariable String field,
            @RequestParam Map<String, String> parameters, @RequestParam(required = false) String search, HttpServletRequest request) {{
        return queries.group(entity, field, fromParameters(parameters), search, "group", request);
    }}

    @PostMapping("/{{entity}}/group-by/{{field}}/filter")
    @PreAuthorize("@filterxAuthorization.authorize(authentication, #entity, 'group.filter')")
    public List<FilterxRequests.GroupResult> groupFilter(@PathVariable String entity, @PathVariable String field,
            @Valid @RequestBody FilterxRequests.FilterRequest body, @RequestParam(required = false) String search, HttpServletRequest request) {{
        return queries.group(entity, field, body, search, "group.filter", request);
    }}

    private FilterxRequests.FilterRequest fromParameters(Map<String, String> parameters) {{
        List<FilterxRequests.FilterCondition> filters = new ArrayList<>();
        for (Map.Entry<String, String> item : parameters.entrySet()) {{
            if (List.of("page", "size", "sort_by", "order", "search").contains(item.getKey()) || item.getValue().isBlank()) continue;
            String field = item.getKey(); String operation = "eq";
            for (String candidate : OPERATIONS) {{ String suffix = "_" + candidate; if (field.endsWith(suffix)) {{ field = field.substring(0, field.length() - suffix.length()); operation = candidate; break; }} }}
            com.fasterxml.jackson.databind.node.JsonNodeFactory factory = com.fasterxml.jackson.databind.node.JsonNodeFactory.instance;
            com.fasterxml.jackson.databind.JsonNode value;
            if (List.of("in", "not_in", "between").contains(operation)) {{ var array = factory.arrayNode(); for (String part : item.getValue().split(",")) array.add(part.trim()); value = array; }}
            else value = factory.textNode(item.getValue());
            filters.add(new FilterxRequests.FilterCondition(field, operation, value));
        }}
        return new FilterxRequests.FilterRequest(filters, null);
    }}

    private Object visibleMetadata(com.fasterxml.jackson.databind.JsonNode entity, String action, HttpServletRequest request) {{
        Object principal = request.getAttribute(FilterxSecurity.IdentityFilter.PRINCIPAL_ATTRIBUTE);
        com.fasterxml.jackson.databind.node.ObjectNode copy = (com.fasterxml.jackson.databind.node.ObjectNode) entity.deepCopy();
        var fields = copy.putArray("fields");
        entity.path("fields").forEach(field -> {{ if (visibility.visible(principal, entity, field.path("name").asText(), action, request)) fields.add(field); }});
        return copy;
    }}
}}
'''


def _render_export_service(package: str) -> str:
    return _package_header(package) + r'''import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.springframework.stereotype.Service;

@Service
public class FilterxExportService {
    private static final int BATCH_SIZE = 250;
    private final FilterxQueryService queries;
    private final ObjectMapper mapper;

    public FilterxExportService(FilterxQueryService queries, ObjectMapper mapper) {
        this.queries = queries; this.mapper = mapper;
    }

    public void write(String entity, FilterxRequests.FilterRequest request, String sortBy, String order, String search,
            String format, HttpServletRequest servletRequest, OutputStream output) throws IOException {
        if ("csv".equals(format)) writeCsv(entity, request, sortBy, order, search, servletRequest, output);
        else if ("xlsx".equals(format)) writeXlsx(entity, request, sortBy, order, search, servletRequest, output);
        else writeJson(entity, request, sortBy, order, search, servletRequest, output);
    }

    private Iterable<Map<String, Object>> rows(String entity, FilterxRequests.FilterRequest request, String sortBy,
            String order, String search, HttpServletRequest servletRequest) {
        return () -> new java.util.Iterator<>() {
            private int page = 1; private java.util.Iterator<Map<String, Object>> current = List.<Map<String, Object>>of().iterator(); private boolean done;
            private void fill() {
                while (!done && !current.hasNext()) {
                    FilterxRequests.PageResponse response = queries.query(entity, request, page++, BATCH_SIZE, sortBy, order, search, "export", servletRequest);
                    current = response.data().iterator();
                    done = response.meta().page() >= response.meta().total_pages();
                }
            }
            public boolean hasNext() { fill(); return current.hasNext(); }
            public Map<String, Object> next() { fill(); return current.next(); }
        };
    }

    private void writeCsv(String entity, FilterxRequests.FilterRequest request, String sortBy, String order, String search,
            HttpServletRequest servletRequest, OutputStream output) throws IOException {
        output.write(new byte[] {(byte) 0xEF, (byte) 0xBB, (byte) 0xBF});
        List<String> fields = new ArrayList<>();
        for (Map<String, Object> row : rows(entity, request, sortBy, order, search, servletRequest)) {
            if (fields.isEmpty()) { fields.addAll(row.keySet()); line(output, fields); }
            List<String> values = new ArrayList<>();
            for (String field : fields) values.add(text(row.get(field)));
            line(output, values);
        }
    }

    private void line(OutputStream output, List<String> values) throws IOException {
        String rendered = values.stream().map(this::csv).collect(java.util.stream.Collectors.joining(",")) + "\r\n";
        output.write(rendered.getBytes(StandardCharsets.UTF_8));
    }

    private String csv(String value) { return value.matches(".*[\",\\r\\n].*") ? "\"" + value.replace("\"", "\"\"") + "\"" : value; }
    private String text(Object value) { try { return value == null ? "" : value instanceof Map || value instanceof List ? mapper.writeValueAsString(value) : String.valueOf(value); } catch (IOException error) { throw new IllegalStateException(error); } }

    private void writeJson(String entity, FilterxRequests.FilterRequest request, String sortBy, String order, String search,
            HttpServletRequest servletRequest, OutputStream output) throws IOException {
        output.write('['); boolean first = true;
        for (Map<String, Object> row : rows(entity, request, sortBy, order, search, servletRequest)) {
            if (!first) output.write(','); first = false; output.write(mapper.writeValueAsBytes(row));
        }
        output.write(']');
    }

    private void writeXlsx(String entity, FilterxRequests.FilterRequest request, String sortBy, String order, String search,
            HttpServletRequest servletRequest, OutputStream output) throws IOException {
        try (SXSSFWorkbook workbook = new SXSSFWorkbook(100)) {
            Sheet sheet = workbook.createSheet("Export"); List<String> fields = new ArrayList<>(); int index = 0;
            for (Map<String, Object> value : rows(entity, request, sortBy, order, search, servletRequest)) {
                if (fields.isEmpty()) { fields.addAll(value.keySet()); Row header = sheet.createRow(index++); for (int column = 0; column < fields.size(); column++) header.createCell(column).setCellValue(fields.get(column)); }
                Row row = sheet.createRow(index++);
                for (int column = 0; column < fields.size(); column++) { Cell cell = row.createCell(column); Object item = value.get(fields.get(column)); if (item instanceof Number number) cell.setCellValue(number.doubleValue()); else if (item instanceof Boolean bool) cell.setCellValue(bool); else cell.setCellValue(text(item)); }
            }
            workbook.write(output); workbook.dispose();
        }
    }
}
'''


def _render_configuration(package: str, rate_limit: int) -> str:
    return _package_header(package) + f'''import io.github.resilience4j.ratelimiter.RateLimiter;
import io.github.resilience4j.ratelimiter.RateLimiterConfig;
import io.github.resilience4j.ratelimiter.RateLimiterRegistry;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.time.Duration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.AnonymousAuthenticationFilter;
import org.springframework.web.filter.OncePerRequestFilter;

@Configuration
@EnableMethodSecurity
@OpenAPIDefinition(info = @Info(title = "FilterX API", version = "filterx-ir/v1"))
public class FilterxConfiguration {{
    @Bean @ConditionalOnMissingBean
    FilterxSecurity.IdentityExtractor filterxIdentityExtractor() {{ return request -> null; }}

    @Bean @ConditionalOnMissingBean
    FilterxSecurity.RowLevelSecurity filterxRowLevelSecurity() {{ return (principal, entity, action, request) -> null; }}

    @Bean @ConditionalOnMissingBean
    FilterxSecurity.FieldVisibility filterxFieldVisibility() {{ return (principal, entity, field, action, request) -> true; }}

    @Bean
    FilterxSecurity.IdentityFilter filterxIdentityFilter(FilterxSecurity.IdentityExtractor extractor) {{ return new FilterxSecurity.IdentityFilter(extractor); }}

    @Bean
    RateLimiter filterxRateLimiter() {{
        RateLimiterConfig config = RateLimiterConfig.custom().limitForPeriod({rate_limit}).limitRefreshPeriod(Duration.ofMinutes(1)).timeoutDuration(Duration.ZERO).build();
        return RateLimiterRegistry.of(config).rateLimiter("filterx-api");
    }}

    @Bean
    OncePerRequestFilter filterxRateLimitFilter(RateLimiter filterxRateLimiter) {{
        return new OncePerRequestFilter() {{
            @Override protected boolean shouldNotFilter(HttpServletRequest request) {{ return !request.getRequestURI().contains("/filterx"); }}
            @Override protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain) throws ServletException, IOException {{
                if (!filterxRateLimiter.acquirePermission()) {{ response.setStatus(429); response.setContentType("application/json"); response.getWriter().write("{{\\\"error\\\":{{\\\"code\\\":\\\"RATE_LIMITED\\\",\\\"message\\\":\\\"Too many FilterX requests.\\\"}}}}"); return; }}
                chain.doFilter(request, response);
            }}
        }};
    }}

    @Bean
    SecurityFilterChain filterxSecurityFilterChain(HttpSecurity http, FilterxSecurity.IdentityFilter identityFilter,
            OncePerRequestFilter filterxRateLimitFilter) throws Exception {{
        http.csrf(csrf -> csrf.disable())
            .headers(headers -> headers.contentTypeOptions(options -> {{}}).frameOptions(frame -> frame.deny()))
            .authorizeHttpRequests(requests -> requests.anyRequest().permitAll())
            .addFilterBefore(identityFilter, AnonymousAuthenticationFilter.class)
            .addFilterAfter(filterxRateLimitFilter, FilterxSecurity.IdentityFilter.class);
        return http.build();
    }}
}}
'''


def _render_errors(package: str) -> str:
    return _package_header(package) + '''import jakarta.validation.ConstraintViolationException;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

class FilterxRequestException extends RuntimeException {
    final String code;
    FilterxRequestException(String code, String message) { super(message); this.code = code; }
}

@RestControllerAdvice
public class FilterxErrorHandler {
    private static final Logger LOG = LoggerFactory.getLogger(FilterxErrorHandler.class);
    private Map<String, Object> body(String code, String message, Object details) {
        return Map.of("error", details == null ? Map.of("code", code, "message", message) : Map.of("code", code, "message", message, "details", details));
    }
    @ExceptionHandler(FilterxRequestException.class)
    ResponseEntity<?> request(FilterxRequestException error) { return ResponseEntity.badRequest().body(body(error.code, error.getMessage(), null)); }
    @ExceptionHandler({MethodArgumentNotValidException.class, ConstraintViolationException.class})
    ResponseEntity<?> validation(Exception error) { return ResponseEntity.badRequest().body(body("VALIDATION_ERROR", "Request validation failed.", error.getMessage())); }
    @ExceptionHandler(Exception.class)
    ResponseEntity<?> unexpected(Exception error) {
        LOG.error("filterx_request_failed type={} message={}", error.getClass().getName(), error.getMessage(), error);
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(body("INTERNAL_ERROR", "Unexpected FilterX error.", null));
    }
}
'''


class SpringBootJPARenderer:
    name = "spring-boot-jpa"
    version = "1.0.0"
    target = RendererTarget.BACKEND

    def _load(self, args: Any) -> tuple[Path, dict[str, Any], FilterxIR]:
        project_root = Path(args.project_root).resolve()
        config_path = Path(args.config).resolve() if args.config else None
        cfg = load_effective_config(project_root, config_path).raw
        ir_path = project_root / cfg["output"].get("ir_file", ".filterx/ir.json")
        if not ir_path.is_file():
            raise ValueError(f"FilterX IR artifact is missing at '{ir_path}'. Run 'filterx scan' first.")
        ir = ir_from_dict(load_json(ir_path))
        if ir.version != "filterx-ir/v1":
            raise ValueError(f"Spring renderer requires filterx-ir/v1, received '{ir.version}'.")
        return project_root, cfg, ir

    def _module_root(self, project_root: Path, spring: Mapping[str, Any]) -> Path:
        configured = str(spring.get("module_path", "."))
        candidate = (project_root / configured).resolve()
        if configured != "." or any((candidate / name).is_file() for name in ("pom.xml", "build.gradle", "build.gradle.kts")):
            if not candidate.is_dir():
                raise ValueError(f"Spring module_path does not exist: '{candidate}'.")
            return candidate
        manifests = sorted({path.parent for pattern in ("pom.xml", "build.gradle", "build.gradle.kts") for path in project_root.glob(f"**/{pattern}")})
        if len(manifests) != 1:
            raise ValueError("Spring module detection is ambiguous. Set backend.spring.module_path to the web/JPA module containing the application class.")
        return manifests[0]

    def _build(self, project_root: Path, spring: Mapping[str, Any]) -> tuple[Path, str, Path, str]:
        module = self._module_root(project_root, spring)
        configured = spring.get("build_tool")
        maven = (module / str(spring.get("pom_file", "pom.xml"))).is_file()
        gradle_candidates = [module / name for name in (str(spring.get("gradle_file")) if spring.get("gradle_file") else "", "build.gradle", "build.gradle.kts") if name]
        gradle_files = list(dict.fromkeys(path for path in gradle_candidates if path.is_file()))
        detected = (["maven"] if maven else []) + (["gradle"] if gradle_files else [])
        if configured:
            detected = [str(configured)]
        if len(detected) != 1:
            raise ValueError("Maven/Gradle detection is ambiguous. Set backend.spring.build_tool and module_path explicitly.")
        tool = detected[0]
        if tool == "maven":
            manifest = module / str(spring.get("pom_file", "pom.xml"))
            if not manifest.is_file(): raise ValueError(f"Maven manifest was not found at '{manifest}'.")
            wrapper = next((path for root in (module, project_root) for name in ("mvnw.cmd", "mvnw") if (path := root / name).is_file()), None)
            command = str(spring.get("maven_command") or wrapper or "mvn")
        else:
            if len(gradle_files) != 1:
                raise ValueError("Gradle Groovy/Kotlin manifest detection is ambiguous. Set backend.spring.gradle_file explicitly.")
            manifest = gradle_files[0]
            wrapper = next((path for root in (module, project_root) for name in ("gradlew.bat", "gradlew") if (path := root / name).is_file()), None)
            command = str(spring.get("gradle_command") or wrapper or "gradle")
        self._require_boot3(manifest, tool)
        return module, tool, manifest, command

    def _require_boot3(self, manifest: Path, tool: str) -> None:
        source = manifest.read_text(encoding="utf-8")
        version: str | None = None
        if tool == "maven":
            root = ET.fromstring(source)
            local = lambda tag: tag.rsplit("}", 1)[-1]
            parent = next((child for child in root if local(child.tag) == "parent"), None)
            if parent is not None:
                values = {local(child.tag): (child.text or "").strip() for child in parent}
                if values.get("groupId") == "org.springframework.boot": version = values.get("version")
            if version is None:
                properties = next((child for child in root if local(child.tag) == "properties"), None)
                if properties is not None:
                    values = {local(child.tag): (child.text or "").strip() for child in properties}
                    version = values.get("spring-boot.version")
        else:
            match = _BOOT_PLUGIN_RE.search(source)
            version = match.group(1) if match else None
        if version is None or not version.startswith("3."):
            raise ValueError(f"Spring Boot 3.x could not be verified in '{manifest}'. FilterX generates Java 17+/jakarta sources only.")

    def _layout(self, project_root: Path, spring: Mapping[str, Any], ir: FilterxIR) -> SpringLayout:
        module, tool, manifest, command = self._build(project_root, spring)
        source_root = (module / str(spring.get("source_root", "src/main/java"))).resolve()
        package = str(spring.get("generated_package", ""))
        if not _JAVA_PACKAGE_RE.fullmatch(package):
            raise ValueError(f"Invalid Java package '{package}' in backend.spring.generated_package.")
        generated_root = source_root.joinpath(*package.split("."))
        application = spring.get("application_class")
        candidates = [path for path in source_root.glob("**/*.java") if _BOOT_APPLICATION_RE.search(path.read_text(encoding="utf-8"))] if source_root.is_dir() else []
        if application:
            application = str(application)
            app_path = source_root.joinpath(*application.split(".")).with_suffix(".java")
            if not app_path.is_file(): raise ValueError(f"Configured Spring application class source was not found: '{app_path}'.")
        elif len(candidates) == 1:
            app_path = candidates[0]
            declaration = _PACKAGE_RE.search(app_path.read_text(encoding="utf-8"))
            if not declaration: raise ValueError(f"Spring application source has no package declaration: '{app_path}'.")
            application = declaration.group(1) + "." + app_path.stem
        else:
            raise ValueError("Spring application class detection is ambiguous. Set backend.spring.application_class explicitly.")
        self._validate_package_path(source_root, app_path)
        app_package = str(application).rsplit(".", 1)[0]
        if package != app_package and not package.startswith(app_package + "."):
            raise ValueError(f"Generated package '{package}' must be inside application component-scan package '{app_package}'.")
        for entity in ir.entities:
            if not _JAVA_PACKAGE_RE.fullmatch(entity.identity.module):
                raise ValueError(f"Entity '{entity.name}' has invalid Java package '{entity.identity.module}' in filterx-ir/v1.")
            entity_path = source_root.joinpath(*entity.identity.module.split("."), f"{entity.name}.java")
            if entity_path.exists(): self._validate_package_path(source_root, entity_path)
        expected = source_root.joinpath(*package.split("."))
        if expected != generated_root:
            raise ValueError("Generated package and directory do not correspond.")
        return SpringLayout(module, source_root, package, generated_root, str(application), tool, manifest, command)

    def _validate_package_path(self, source_root: Path, java_file: Path) -> None:
        declaration = _PACKAGE_RE.search(java_file.read_text(encoding="utf-8"))
        if not declaration: raise ValueError(f"Java source has no package declaration: '{java_file}'.")
        expected = source_root.joinpath(*declaration.group(1).split("."), java_file.name).resolve()
        if expected != java_file.resolve():
            raise ValueError(f"Java package-directory mismatch: '{java_file}' declares '{declaration.group(1)}' but should be at '{expected}'.")

    def _dependencies(self, layout: SpringLayout, spring: Mapping[str, Any]) -> PatchOp:
        managed = [
            ("org.springframework.boot", "spring-boot-starter-web"),
            ("org.springframework.boot", "spring-boot-starter-data-jpa"),
            ("org.springframework.boot", "spring-boot-starter-validation"),
            ("org.springframework.boot", "spring-boot-starter-security"),
        ]
        pinned = [
            ("org.springdoc", "springdoc-openapi-starter-webmvc-ui", str(spring["springdoc_version"])),
            ("io.github.resilience4j", "resilience4j-spring-boot3", str(spring["resilience4j_version"])),
            ("org.apache.poi", "poi-ooxml", str(spring["poi_version"])),
        ]
        path = layout.manifest.relative_to(layout.module_root).as_posix()
        if layout.build_tool == "maven":
            dependencies = [{"group_id": group, "artifact_id": name} for group, name in managed]
            dependencies.extend({"group_id": group, "artifact_id": name, "version": version} for group, name, version in pinned)
            return PatchOp(kind="structured_merge", path=path, owner="host", structured_format="xml", merge={"dependencies": dependencies})
        dependencies = [{"configuration": "implementation", "group": group, "name": name} for group, name in managed]
        dependencies.extend({"configuration": "implementation", "group": group, "name": name, "version": version} for group, name, version in pinned)
        return PatchOp(kind="structured_merge", path=path, owner="host", structured_format="gradle", merge={"dependencies": dependencies})

    def _operations(self, project_root: Path, cfg: Mapping[str, Any], ir: FilterxIR, layout: SpringLayout) -> list[PatchOp]:
        spring = cfg["backend"]["spring"]
        files = {
            "FilterxMetadata.java": _render_metadata(layout.generated_package, ir),
            "FilterxDtos.java": _render_dtos(layout.generated_package, ir),
            "FilterxRequests.java": _render_requests(layout.generated_package),
            "FilterxSecurity.java": _render_security(layout.generated_package),
            "FilterxSpecifications.java": _render_specifications(layout.generated_package),
            "FilterxQueryService.java": _render_query_service(layout.generated_package, int(spring["max_query_cost"])),
            "FilterxExportService.java": _render_export_service(layout.generated_package),
            "FilterxController.java": _render_controller(layout.generated_package, str(cfg["backend"].get("api_prefix", "/api"))),
            "FilterxConfiguration.java": _render_configuration(layout.generated_package, int(spring["rate_limit_per_minute"])),
            "FilterxErrorHandler.java": _render_errors(layout.generated_package),
        }
        operations = [PatchOp(kind="generated_file", path=(layout.generated_root / name).relative_to(layout.module_root).as_posix(), content=content) for name, content in files.items()]
        operations.append(self._dependencies(layout, spring))
        return operations

    def install(self, args: Any) -> int:
        try:
            project_root, cfg, ir = self._load(args)
            spring = cfg["backend"]["spring"]
            layout = self._layout(project_root, spring, ir)
            operations = self._operations(project_root, cfg, ir, layout)
        except (ValueError, ET.ParseError) as exc:
            print(json.dumps({"errors": [{"code": "SPRING_CONFIGURATION_INVALID", "message": str(exc)}]}, indent=2))
            return 2
        result = apply_patch_operations(
            project_root=layout.module_root,
            operations=operations,
            manifest_path=project_root / cfg["safety"]["idempotency_manifest"],
            patch_dir=project_root / cfg["output"]["patch_dir"],
            dry_run=bool(getattr(args, "dry_run", False)),
            check_mode=bool(getattr(args, "check", False)),
            strict_conflict_mode=bool(cfg["safety"].get("strict_conflict_mode", True)),
            description="backend.install.spring-boot-jpa",
        )
        print(json.dumps({"framework": self.name, "dry_run": result.dry_run, "patch_id": result.patch_id, "applied_ops": result.applied_ops, "skipped_ops": result.skipped_ops, "touched_files": result.touched_files, "issues": [vars(issue) for issue in result.issues]}, indent=2))
        return 3 if result.has_conflicts else 0

    def compile_command(self, layout: SpringLayout, spring: Mapping[str, Any]) -> tuple[str, ...]:
        if layout.build_tool == "maven":
            return (layout.command, *map(str, spring.get("maven_args", [])), "-DskipTests", "compile")
        return (layout.command, *map(str, spring.get("gradle_args", [])), "classes", "--no-daemon")

    def validate(self, args: Any) -> int:
        try:
            project_root, cfg, ir = self._load(args)
            spring = cfg["backend"]["spring"]
            layout = self._layout(project_root, spring, ir)
        except (ValueError, ET.ParseError) as exc:
            print(json.dumps({"errors": [{"code": "SPRING_CONFIGURATION_INVALID", "message": str(exc)}]}, indent=2))
            return 4
        required = ("FilterxMetadata.java", "FilterxDtos.java", "FilterxRequests.java", "FilterxSecurity.java", "FilterxSpecifications.java", "FilterxQueryService.java", "FilterxExportService.java", "FilterxController.java", "FilterxConfiguration.java", "FilterxErrorHandler.java")
        errors = [{"code": "SPRING_GENERATED_FILE_MISSING", "path": str(layout.generated_root / name)} for name in required if not (layout.generated_root / name).is_file()]
        command = self.compile_command(layout, spring)
        if not errors:
            try:
                result = subprocess.run(command, cwd=layout.module_root, capture_output=True, text=True, timeout=float(spring["compile_timeout_seconds"]), check=False)
                if result.returncode != 0:
                    errors.append({"code": "SPRING_COMPILE_FAILED", "message": "Generated Spring sources did not compile. Fix the reported host/generated source errors and rerun filterx backend validate.", "command": list(command), "exit_code": result.returncode, "stdout": result.stdout[-8000:], "stderr": result.stderr[-8000:]})
            except FileNotFoundError:
                errors.append({"code": "SPRING_BUILD_TOOL_MISSING", "message": f"Build command '{command[0]}' was not found. Add the project wrapper or install {layout.build_tool}.", "command": list(command)})
            except subprocess.TimeoutExpired:
                errors.append({"code": "SPRING_COMPILE_TIMEOUT", "message": "Host compile verification exceeded backend.spring.compile_timeout_seconds.", "command": list(command)})
        payload = {"errors": errors, "warnings": [], "error_count": len(errors), "warning_count": 0, "compile_command": list(command)}
        print(json.dumps(payload, indent=2))
        return 4 if errors else 0

    def remove(self, args: Any) -> int:
        print(json.dumps({"errors": [{"code": "SPRING_REMOVE_USE_ROLLBACK", "message": "Use filterx rollback with the Spring install patch id so generated sources and parser-backed manifest changes are restored together."}]}, indent=2))
        return 2
