"""Add saved_filters table

Revision ID: e55b23277609
Revises: 91286d61adeb
Create Date: 2026-02-03 18:36:19.091883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55b23277609'
down_revision: Union[str, Sequence[str], None] = '91286d61adeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('sort_by', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.String(length=4), nullable=True),
    sa.Column('page_size', sa.Integer(), nullable=True),
    sa.Column('search_query', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_filters_id'), 'saved_filters', ['id'], unique=False)
    op.create_index(op.f('ix_saved_filters_model_name'), 'saved_filters', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_filters_model_name'), table_name='saved_filters')
    op.drop_index(op.f('ix_saved_filters_id'), table_name='saved_filters')
    op.drop_table('saved_filters')
    # ### end Alembic commands ###
