"""Add filter_tree to saved_filters

Revision ID: ffe0aeae74f8
Revises: e55b23277609
Create Date: 2026-02-25 00:34:14.842431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe0aeae74f8'
down_revision: Union[str, Sequence[str], None] = 'e55b23277609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_filters', sa.Column('filter_tree', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_filters', 'filter_tree')
    # ### end Alembic commands ###
